import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'
import { useSoftBaker } from 'use-softbaker'
import Swal from 'sweetalert2'
import { Button } from '@chakra-ui/react'


export default function Home() {

  const { 
    signIn, signOut, auth, authLoading, user, createDoc, updateDoc, db, 
    deposit, showWallet,
    balanceInUsd, 
    balancePendingInUsd,
    unconfirmedDepositsCount
  } = useSoftBaker()

  useEffect(() => {
    console.log("User:", user)
  }, [user])

  const [ showPay, setShowPay ] = useState<boolean>()
  const handleSignIn = () => {
    
   //return
    signIn("Sign In to save your shipment", "Sign Up to save your shipment")
    .then(user => {
      Swal.fire({
        icon: 'success',
        title: "Sign Successfull!",
        text: `Email: ${user.email} | ${user.uid}`
      })
    })
    .catch(e => {
      Swal.fire({
        icon: 'error',
        title: "Sign In Error",
        text: e.message
      })
    })
  }

  const handleDeposit = () => {

    deposit(10, "Sign In to save your shipment", "Sign Up to save your shipment")
    .then((user: any) => {
      Swal.fire({
        icon: 'success',
        title: "Sign Successfull!",
        text: `Email: ${user.email} | ${user.uid}`
      })
    })
    .catch((e: Error) => {
      Swal.fire({
        icon: 'error',
        title: "Sign In Error",
        text: e.message
      })
    })
  }

  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.description}>
          <p onClick={ handleDeposit }>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx: {user?.email}, {user?.displayName}</code>
          </p>
          <Button onClick={handleDeposit} mb="0.5rem">
            Deposit
          </Button>
          <Button onClick={() => {
            showWallet(11)
          }} mb="0.5rem">
            Show Wallet
          </Button>
          {
            user? <Button onClick={() => {
              signOut()
            }} mb="0.5rem">
              Sign Out
            </Button> : null
          }
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Docs <span>-&gt;</span>
            </h2>
            <p>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Learn <span>-&gt;</span>
            </h2>
            <p>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Templates <span>-&gt;</span>
            </h2>
            <p>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2>
              Deploy <span>-&gt;</span>
            </h2>
            <p>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main>
    </>
  )
}
